apiVersion: apps/v1 

kind: Deployment 

metadata: 

  name: nginx-webapp 

spec: 

  replicas: 3 

  selector: 

    matchLabels: 

      app: nginx 

  template: 

    metadata: 

      labels: 

        app: nginx 

    spec: 

      containers: 

      - name: nginx 

        image: mhorni/nginx-pod-info:v2.1 

        ports: 

        - containerPort: 80 

        env: 

        - name: POD_NAME 

          valueFrom: 

            fieldRef: 

              fieldPath: metadata.name 

        - name: NODE_NAME 

          valueFrom: 

            fieldRef: 

              fieldPath: spec.nodeName